# Cloud Build configuration for Project Agent

steps:
  # Build Python services - using root context with Dockerfile path
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-chat-api:latest', '-f', 'services/api/chat/Dockerfile', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-inventory-api:latest', '-f', 'services/api/inventory/Dockerfile', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-documents-api:latest', '-f', 'services/api/documents/Dockerfile', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-admin-api:latest', '-f', 'services/api/admin/Dockerfile', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-upload-api:latest', '-f', 'services/api/upload/Dockerfile', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-ingestion-worker:latest', '-f', 'services/workers/ingestion/Dockerfile', '.']
    dir: '.'

  # Build Next.js web portal
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd web/portal
        npm ci
        npm run build
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/project-agent-web:latest', './web/portal']
    dir: '.'

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-chat-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-inventory-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-documents-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-admin-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-upload-api:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-ingestion-worker:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/project-agent-web:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-chat-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-chat-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8081'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,REGION=us-central1,GCS_DOC_BUCKET=ta-test-docs-uat,GCS_THUMB_BUCKET=ta-test-thumbs-uat,FIRESTORE_DB=(default),VECTOR_INDEX=89915861896265728,NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-inventory-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-inventory-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8082'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,REGION=us-central1,GCS_DOC_BUCKET=ta-test-docs-uat,GCS_THUMB_BUCKET=ta-test-thumbs-uat,FIRESTORE_DB=(default),NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-documents-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-documents-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8083'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,REGION=us-central1,GCS_DOC_BUCKET=ta-test-docs-uat,GCS_THUMB_BUCKET=ta-test-thumbs-uat,FIRESTORE_DB=(default),NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-admin-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-admin-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8084'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,REGION=us-central1,GCS_DOC_BUCKET=ta-test-docs-uat,GCS_THUMB_BUCKET=ta-test-thumbs-uat,FIRESTORE_DB=(default),NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-upload-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-upload-api:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8085'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GCP_PROJECT=$PROJECT_ID,REGION=us-central1,GCS_DOC_BUCKET=ta-test-docs-uat,GCS_THUMB_BUCKET=ta-test-thumbs-uat,FIRESTORE_DB=(default),NODE_ENV=production'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-ingestion-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-ingestion-worker:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '5'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'project-agent-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/project-agent-web:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,GCP_PROJECT=$PROJECT_ID'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout
timeout: '1200s'

# Images to store in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/project-agent-chat-api:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-inventory-api:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-documents-api:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-admin-api:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-upload-api:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-ingestion-worker:latest'
  - 'gcr.io/$PROJECT_ID/project-agent-web:latest'
